### DISCUSSION TITLE
Copy to clipboard buttons size and alignment

### DISCUSSION THREAD

**Discussion by pwnedshell** [expressive-code/expressive-code#404] [Feature Requests]
Copy to clipboard buttons from the mobile view are larger than from the desktop view (with the same approximate width).

![image](https://github.com/expressive-code/expressive-code/assets/55540142/18a91b85-fd1d-44e1-88c8-92a67d5f04b0)

![image](https://github.com/expressive-code/expressive-code/assets/55540142/b60c0c1e-6b10-4a94-b1e6-a05a03cc22d3)

Also, if the codePaddingBlock property is changed, the height of the button is not calculated correctly.

![image](https://github.com/expressive-code/expressive-code/assets/55540142/d198ae63-8038-4916-bf67-68a358d228de)

![image](https://github.com/expressive-code/expressive-code/assets/55540142/f7acf246-27a0-42f6-a753-20a0d23d77c6)

**Comment by hippotastic** [comment]
Hello and welcome! Thank you for this report and the helpful screenshots.

That the button size increases on mobile is an accessibility feature to increase its tap size. However, I also agree that it doesn't look as nice on mobile due to this change.

What would you think about the alternative of still increasing the tap area, but keeping the size of the button consistent? This is a common solution to this problem on mobile and could also work for EC.

Regarding the size of the button when reducing the block padding to a minimal value like the one you've shown: There is no calculation happening at all right now. It's a fixed size that satisfies accessibility guidelines. I could try to calculate the size accordingly so that it hopefully doesn't peek out of the frame (again while keeping the actual tap area the same), but depending on how small you make the padding, the button might look very tiny. Can you show an example of the size you'd like it to have? It should be possible to change the size in your browser's DevTools and take a screenshot.

**Comment by pwnedshell** [comment]
Yeah I think it would be nice to have a smaller button on mobile/tablet devices keeping the same tap area for accessibility.

What I tried (as a quick patch) is to scale the button smaller:

```html
<Code code=`${content}` lang="html" class="codeblock" frame="none" />
```

```css
@media (width <= 1024px) {
  .codeblock .copy {
	  transform: scale(.90);
  }
}
@media (width <= 768px) {
  .codeblock .copy {
	  transform: scale(.80);
  }
}
@media (width <= 640px) {
  .codeblock .copy {
	  transform: scale(.70);
  }
}
```

\>1024px default 1 rem of padding:
![image](https://github.com/expressive-code/expressive-code/assets/55540142/320c5874-677f-4b8d-afdd-44349d4d2174)

\>768px default 1 rem of padding:
![image](https://github.com/expressive-code/expressive-code/assets/55540142/c0c698a9-164f-4b79-9838-8feb17b03905)

\>640px default 1 rem of padding:
![image](https://github.com/expressive-code/expressive-code/assets/55540142/fdc83c40-0e57-49fb-9dde-6bf4705b1bb5)

<640px default 1 rem of padding:
![image](https://github.com/expressive-code/expressive-code/assets/55540142/573bbd81-58c4-4437-ba11-901b81c98fd8)

One problem of scaling is that the "Copied!" label when clicked causes the button to move to the left (it then returns to its position):

![image](https://github.com/expressive-code/expressive-code/assets/55540142/86ed80a6-f352-446a-a735-bfc134e60c1f)

An example of what I would like (in my specific case) should be something like this (with .5rem of padding):

```css
.codeblock .copy {
  margin-top: -7px;
  transform: scale(.80);
}

@media (width <= 1024px) {
.codeblock .copy {
	margin-top: -8px;
	transform: scale(.70);
}
}
@media (width <= 768px) {
.codeblock .copy {
	margin-top: -8px;
	transform: scale(.65);
}
}
@media (width <= 640px) {
.codeblock .copy {
	transform: scale(.55);
}
}
```

\>640px  .5 rem of padding:
![image](https://github.com/expressive-code/expressive-code/assets/55540142/c150e215-8f32-407b-8a61-bb9fef2aa15e)

Still a problem as needs to be scalable taking in consideration the padding and the actual code height but I hope it will serve as an example.

I don't know how "bad practice" it would be, but perhaps a ShowCopyToClipboardButtonOnMobile option would also be interesting?

Thanks!
