### ISSUE TITLE
msg.match is undefined

### ISSUE THREAD

**Issue by angelovdev** [expressive-code/expressive-code#175]
The build works locally with bun but fails in CI with this error:

```sh
bun run build
astro check && astro build
msg.match is not a function. (In 'msg.match(/ec\.config\.mjs.*(imported from|resolved id)/)', 'msg.match' is undefined)
  Stack trace:
    at <anonymous> (/builds/x/y/node_modules/astro-expressive-code/dist/index.js:23:22)
```

Using starlight from Astro.

Version of expressive code is 0.33.5.

Part of the GitLab CI:

```yaml
stages:
  - deploy

image: oven/bun

deploy_review:
  stage: deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://xyz.xyz
  before_script:
    - bun install --frozen-dependencies
    - bun install -g abc@3.7.1
  script:
    - bun run build
    - .ci/deploy_review.sh
  artifacts:
    paths:
      - public
  only:
    - branches
  except:
    - main
```
