### ISSUE TITLE
Make css custom properties easier to customize

### ISSUE THREAD

**Issue by hirasso** [expressive-code/expressive-code#21]
I tried to customize the background color of the copy code tooltip by changing the prop `--tooltip-bg`.

It's shipped using this rule:

```css
.ec.ec-of75f .copy .feedback {
	--tooltip-bg: #177d07;
}
```

I see two problems with this:

- The `.ec-{hash}` changes sometimes (when I switch the shiki theme? When I build? I don't know exactly)
- The `.ec.ec-of75f` is pretty specific

To overwrite it, I need to use `.ec.expressive-code` to avoid having to use `!important`:

```css
.ec.expressive-code .copy .feedback {
	--tooltip-bg: rebeccapurple;
}
```

A solution to make these properties easily adjustable would be to put them at the root of every instance of `.expressive-code`:

```css
.expressive-code {
	--copy-tooltip-bg: #177d07;
}
```
