### ISSUE TITLE
Support override the height of code block

### ISSUE THREAD

**Issue by lawvs** [expressive-code/expressive-code#241]
I need to restrict the height of excessively long code in the document, but I couldn't find the corresponding property within `styleOverrides`.

In the end, I solved this problem using custom styles, but I hope that expressive-code will support limiting the height of the code block in the future.

Also related to https://github.com/expressive-code/expressive-code/issues/226

```css
.expressive-code pre {
  max-height: min(68vh, 1000px) !important;
  overflow: auto;
}
.expressive-code pre::-webkit-scrollbar-corner {
  display: none;
}
```

<img width="691" alt="Screenshot 2024-09-02 at 13 51 49" src="https://github.com/user-attachments/assets/6746495b-29d1-4df4-b6c6-7d68270a9a13">

**Comment by hippotastic** [comment]
Hello and welcome! :)

I really like the idea of being able to provide a maximum height for code blocks, especially for sites that have very long code examples. It's awesome that you already built your own solution using CSS, which I just tested locally and it seemed to work well! The only changes I'd probably make is using `lh` as unit to specify a desired maximum number of lines instead of pixels, and I'd make sure that there is a lower limit to `max-height` so that code blocks will never fully collapse with very small viewport heights.

Is there a particular reason why you had to add `!important` to the `max-height` property value? To my knowledge, I'm not setting `max-height` anywhere in Expressive Code, so it shouldn't really be necessary.

With your solution, we now have two possible ways to reduce the impact of very long code blocks on the document flow - the expand/collapse approach described in #226, and your max-height approach. I can see use cases for both options and will think about how to integrate these into Expressive Code.

I'll keep this open as a reminder for the feature idea and to allow further discussion if needed. Thanks again!

**Comment by lawvs** [comment]
> Is there a particular reason why you had to add `!important` to the `max-height` property value? To my knowledge, I'm not setting `max-height` anywhere in Expressive Code, so it shouldn't really be necessary.

Yes, this problem is very weird, but this style cannot be directly applied to pre tag, even on the expressive-code documentation site.

https://github.com/user-attachments/assets/cd0c9b2a-62a9-45f9-b22e-03021f149ddc

```css
/* This CSS is not works */
.expressive-code pre {
  max-height: min(68vh, 1000px);
  overflow: auto;
}

/* This CSS is works */
.expressive-code pre {
  max-height: min(68vh, 1000px) !important;
  overflow: auto;
} 
/* This CSS is works */
.expressive-code .frame pre {
  max-height: min(68vh, 1000px);
  overflow: auto;
}
```
