### ISSUE TITLE
Usage outside of Astro and Next

### ISSUE THREAD

**Issue by ijpatricio** [expressive-code/expressive-code#246]
Hey everyone,

To begin with, thank you for this amazing work, impressive!

As stated [here](https://github.com/expressive-code/expressive-code/blob/main/packages/expressive-code/README.md) , I tried to pursuit this path to render this in an agnostic page, with PHP/Laravel.

I'm able to run the Node, no problem. The thing is that this code (got it from above link)...

```ts
import { ExpressiveCode, ExpressiveCodeConfig } from 'expressive-code'
import { toHtml } from 'expressive-code/hast'

const ec = new ExpressiveCode()

// Get base styles that should be included on the page
// (they are independent of the rendered code blocks)
const baseStyles = await ec.getBaseStyles()

// Render some example code to AST
const { renderedGroupAst, styles } = await ec.render({
  code: 'console.log("Hello world!")',
  language: 'js',
  meta: '',
})

// Convert the rendered AST to HTML
let htmlContent = toHtml(renderedGroupAst)

// Collect styles and add them before the HTML content
const stylesToPrepend: string[] = []
stylesToPrepend.push(baseStyles)
stylesToPrepend.push(...styles)
if (stylesToPrepend.length) {
  htmlContent = `<style>${[...stylesToPrepend].join('')}</style>${htmlContent}`
}

// Output HTML to the console
console.log(htmlContent)
```

...produces unstyled output.

That is because (it seems to me) that I'm missing a lot of css variables ??

Look at the output:

```css
<style>.expressive-code {
    font-family: var(--ec-uiFontFml);
    font-size: var(--ec-uiFontSize);
    font-weight: var(--ec-uiFontWg);
    line-height: var(--ec-uiLineHt);
    text-size-adjust: none;
    -webkit-text-size-adjust: none
}

.expressive-code *:not(path) {
    all: revert;
    box-sizing: border-box
}

.expressive-code pre {
    display: flex;
    margin: 0;
    padding: 0;
    border: var(--ec-brdWd) solid var(--ec-brdCol);
    border-radius: calc(var(--ec-brdRad) + var(--ec-brdWd));
    background: var(--ec-codeBg)
}

.expressive-code pre:focus-visible {
    outline: 3px solid var(--ec-focusBrd);
    outline-offset: -3px
}

.expressive-code pre > code {
    all: unset;
    display: block;
    flex: 1 0 100%;
    padding: var(--ec-codePadBlk) 0;
    color: var(--ec-codeFg);
    font-family: var(--ec-codeFontFml);
    font-size: var(--ec-codeFontSize);
    font-weight: var(--ec-codeFontWg);
    line-height: var(--ec-codeLineHt)
}

.expressive-code pre {
    overflow-x: auto
}

.expressive-code pre.wrap .ec-line .code {
    white-space: pre-wrap;
    overflow-wrap: break-word;
    min-width: min(20ch, var(--ecMaxLine, 20ch))
}

.expressive-code pre.wrap .ec-line .code span.indent {
    white-space: pre
}

.expressive-code pre::-webkit-scrollbar, .expressive-code pre::-webkit-scrollbar-track {
    background-color: inherit;
    border-radius: calc(var(--ec-brdRad) + var(--ec-brdWd));
    border-top-left-radius: 0;
    border-top-right-radius: 0
}

.expressive-code pre::-webkit-scrollbar-thumb {
    background-color: var(--ec-sbThumbCol);
    border: 4px solid transparent;
    background-clip: content-box;
    border-radius: 10px
}

.expressive-code pre::-webkit-scrollbar-thumb:hover {
    background-color: var(--ec-sbThumbHoverCol)
}

.expressive-code .ec-line {
    direction: ltr;
    unicode-bidi: isolate;
    display: grid;
    grid-template-areas:'gutter code';
    grid-template-columns:auto 1fr;
    position: relative
}

.expressive-code .ec-line .gutter {
    grid-area: gutter;
    color: var(--ec-gtrFg)
}

.expressive-code .ec-line .gutter > * {
    pointer-events: none;
    user-select: none;
    -webkit-user-select: none
}

.expressive-code .ec-line .gutter ~ .code {
    --ecLineBrdCol: var(--ec-gtrBrdCol)
}

.expressive-code .ec-line.highlight .gutter {
    color: var(--ec-gtrHlFg)
}

.expressive-code .ec-line .code {
    grid-area: code;
    position: relative;
    box-sizing: content-box;
    padding-inline-start: calc(var(--ecIndent, 0ch) + var(--ec-codePadInl) - var(--ecGtrBrdWd));
    padding-inline-end: var(--ec-codePadInl);
    text-indent: calc(var(--ecIndent, 0ch) * -1)
}

.expressive-code .ec-line .code::before, .expressive-code .ec-line .code::after, .expressive-code .ec-line .code :where(*) {
    text-indent: 0
}

.expressive-code .ec-line .code {
    --ecGtrBrdWd: var(--ec-gtrBrdWd);
    border-inline-start: var(--ecGtrBrdWd) solid var(--ecLineBrdCol, transparent)
}

.expressive-code :nth-child(1 of .ec-line) .code {
    padding-inline-end: calc(2rem + var(--ec-codePadInl))
}

.expressive-code .sr-only {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border-width: 0
}

.expressive-code .ec-line.mark {
    --tmLineBgCol: var(--ec-tm-markBg)
}

.expressive-code .ec-line.mark .code {
    --ecLineBrdCol: var(--ec-tm-markBrdCol)
}

.expressive-code .ec-line.ins {
    --tmLineBgCol: var(--ec-tm-insBg);
    --tmLabel: var(--ec-tm-insDiffIndContent)
}

.expressive-code .ec-line.ins .code {
    --ecLineBrdCol: var(--ec-tm-insBrdCol)
}

.expressive-code .ec-line.ins .code::before {
    color: var(--ec-tm-insDiffIndCol)
}

.expressive-code .ec-line.del {
    --tmLineBgCol: var(--ec-tm-delBg);
    --tmLabel: var(--ec-tm-delDiffIndContent)
}

.expressive-code .ec-line.del .code {
    --ecLineBrdCol: var(--ec-tm-delBrdCol)
}

.expressive-code .ec-line.del .code::before {
    color: var(--ec-tm-delDiffIndCol)
}

.expressive-code .ec-line.mark, .expressive-code .ec-line.ins, .expressive-code .ec-line.del {
    background: var(--tmLineBgCol)
}

.expressive-code .ec-line.mark .code, .expressive-code .ec-line.ins .code, .expressive-code .ec-line.del .code {
    --ecGtrBrdWd: var(--ec-tm-lineMarkerAccentWd)
}

.expressive-code .ec-line.mark .code::before, .expressive-code .ec-line.ins .code::before, .expressive-code .ec-line.del .code::before {
    display: block;
    position: absolute;
    left: 0;
    box-sizing: border-box;
    content: var(--tmLabel, ' ');
    padding-inline-start: var(--ec-tm-lineDiffIndMargLeft);
    text-align: center;
    white-space: pre
}

.expressive-code .ec-line.mark.tm-label .code::before, .expressive-code .ec-line.ins.tm-label .code::before, .expressive-code .ec-line.del.tm-label .code::before {
    background: var(--ecLineBrdCol);
    padding: 0 calc(var(--ec-tm-lineMarkerLabelPadInl) + var(--ec-tm-lineMarkerAccentWd)) 0 var(--ec-tm-lineMarkerLabelPadInl);
    color: var(--ec-tm-lineMarkerLabelCol)
}

.expressive-code .ec-line mark {
    --tmInlineBgCol: var(--ec-tm-markBg);
    --tmInlineBrdCol: var(--ec-tm-markBrdCol)
}

.expressive-code .ec-line ins {
    --tmInlineBgCol: var(--ec-tm-insBg);
    --tmInlineBrdCol: var(--ec-tm-insBrdCol)
}

.expressive-code .ec-line del {
    --tmInlineBgCol: var(--ec-tm-delBg);
    --tmInlineBrdCol: var(--ec-tm-delBrdCol)
}

.expressive-code .ec-line mark, .expressive-code .ec-line ins, .expressive-code .ec-line del {
    all: unset;
    display: inline-block;
    position: relative;
    --tmBrdL: var(--ec-tm-inlMarkerBrdWd);
    --tmBrdR: var(--ec-tm-inlMarkerBrdWd);
    --tmRadL: var(--ec-tm-inlMarkerBrdRad);
    --tmRadR: var(--ec-tm-inlMarkerBrdRad);
    margin-inline: 0.025rem;
    padding-inline: var(--ec-tm-inlMarkerPad);
    border-radius: var(--tmRadL) var(--tmRadR) var(--tmRadR) var(--tmRadL);
    background: var(--tmInlineBgCol);
    background-clip: padding-box
}

.expressive-code .ec-line mark.open-start, .expressive-code .ec-line ins.open-start, .expressive-code .ec-line del.open-start {
    margin-inline-start: 0;
    padding-inline-start: 0;
    --tmBrdL: 0px;
    --tmRadL: 0
}

.expressive-code .ec-line mark.open-end, .expressive-code .ec-line ins.open-end, .expressive-code .ec-line del.open-end {
    margin-inline-end: 0;
    padding-inline-end: 0;
    --tmBrdR: 0px;
    --tmRadR: 0
}

.expressive-code .ec-line mark::before, .expressive-code .ec-line ins::before, .expressive-code .ec-line del::before {
    content: '';
    position: absolute;
    pointer-events: none;
    display: inline-block;
    inset: 0;
    border-radius: var(--tmRadL) var(--tmRadR) var(--tmRadR) var(--tmRadL);
    border: var(--ec-tm-inlMarkerBrdWd) solid var(--tmInlineBrdCol);
    border-inline-width: var(--tmBrdL) var(--tmBrdR)
}

.expressive-code .frame {
    all: unset;
    position: relative;
    display: block;
    --header-border-radius: calc(var(--ec-brdRad) + var(--ec-brdWd));
    --tab-border-radius: calc(var(--ec-frm-edTabBrdRad) + var(--ec-brdWd));
    --button-spacing: 0.4rem;
    --code-background: var(--ec-frm-edBg);
    border-radius: var(--header-border-radius);
    box-shadow: var(--ec-frm-frameBoxShdCssVal)
}

.expressive-code .frame .header {
    display: none;
    z-index: 1;
    position: relative;
    border-radius: var(--header-border-radius) var(--header-border-radius) 0 0
}

.expressive-code .frame.has-title pre, .expressive-code .frame.has-title code, .expressive-code .frame.is-terminal pre, .expressive-code .frame.is-terminal code {
    border-top: none;
    border-top-left-radius: 0;
    border-top-right-radius: 0
}

.expressive-code .frame .title:empty:before {
    content: '\a0'
}

.expressive-code .frame.has-title:not(.is-terminal) {
    --button-spacing: calc(1.9rem + 2 * (var(--ec-uiPadBlk) + var(--ec-frm-edActTabIndHt)))
}

.expressive-code .frame.has-title:not(.is-terminal) .title {
    position: relative;
    color: var(--ec-frm-edActTabFg);
    background: var(--ec-frm-edActTabBg);
    background-clip: padding-box;
    margin-block-start: var(--ec-frm-edTabsMargBlkStart);
    padding: calc(var(--ec-uiPadBlk) + var(--ec-frm-edActTabIndHt)) var(--ec-uiPadInl);
    border: var(--ec-brdWd) solid var(--ec-frm-edActTabBrdCol);
    border-radius: var(--tab-border-radius) var(--tab-border-radius) 0 0;
    border-bottom: none;
    overflow: hidden
}

.expressive-code .frame.has-title:not(.is-terminal) .title::after {
    content: '';
    position: absolute;
    pointer-events: none;
    inset: 0;
    border-top: var(--ec-frm-edActTabIndHt) solid var(--ec-frm-edActTabIndTopCol);
    border-bottom: var(--ec-frm-edActTabIndHt) solid var(--ec-frm-edActTabIndBtmCol)
}

.expressive-code .frame.has-title:not(.is-terminal) .header {
    display: flex;
    background: linear-gradient(to top, var(--ec-frm-edTabBarBrdBtmCol) var(--ec-brdWd), transparent var(--ec-brdWd)), linear-gradient(var(--ec-frm-edTabBarBg), var(--ec-frm-edTabBarBg));
    background-repeat: no-repeat;
    padding-inline-start: var(--ec-frm-edTabsMargInlStart)
}

.expressive-code .frame.has-title:not(.is-terminal) .header::before {
    content: '';
    position: absolute;
    pointer-events: none;
    inset: 0;
    border: var(--ec-brdWd) solid var(--ec-frm-edTabBarBrdCol);
    border-radius: inherit;
    border-bottom: none
}

.expressive-code .frame.is-terminal {
    --button-spacing: calc(1.9rem + var(--ec-brdWd) + 2 * var(--ec-uiPadBlk));
    --code-background: var(--ec-frm-trmBg)
}

.expressive-code .frame.is-terminal .header {
    display: flex;
    align-items: center;
    justify-content: center;
    padding-block: var(--ec-uiPadBlk);
    padding-block-end: calc(var(--ec-uiPadBlk) + var(--ec-brdWd));
    position: relative;
    font-weight: 500;
    letter-spacing: 0.025ch;
    color: var(--ec-frm-trmTtbFg);
    background: var(--ec-frm-trmTtbBg);
    border: var(--ec-brdWd) solid var(--ec-brdCol);
    border-bottom: none
}

.expressive-code .frame.is-terminal .header::before {
    content: '';
    position: absolute;
    pointer-events: none;
    left: var(--ec-uiPadInl);
    width: 2.1rem;
    height: 0.56rem;
    line-height: 0;
    background-color: var(--ec-frm-trmTtbDotsFg);
    opacity: var(--ec-frm-trmTtbDotsOpa);
    -webkit-mask-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 60 16' preserveAspectRatio='xMidYMid meet'%3E%3Ccircle cx='8' cy='8' r='8'/%3E%3Ccircle cx='30' cy='8' r='8'/%3E%3Ccircle cx='52' cy='8' r='8'/%3E%3C/svg%3E");
    -webkit-mask-repeat: no-repeat;
    mask-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 60 16' preserveAspectRatio='xMidYMid meet'%3E%3Ccircle cx='8' cy='8' r='8'/%3E%3Ccircle cx='30' cy='8' r='8'/%3E%3Ccircle cx='52' cy='8' r='8'/%3E%3C/svg%3E");
    mask-repeat: no-repeat
}

.expressive-code .frame.is-terminal .header::after {
    content: '';
    position: absolute;
    pointer-events: none;
    inset: 0;
    border-bottom: var(--ec-brdWd) solid var(--ec-frm-trmTtbBrdBtmCol)
}

.expressive-code .frame pre {
    background: var(--code-background)
}

.expressive-code .copy {
    display: flex;
    gap: 0.25rem;
    flex-direction: row;
    position: absolute;
    inset-block-start: calc(var(--ec-brdWd) + var(--button-spacing));
    inset-inline-end: calc(var(--ec-brdWd) + var(--ec-uiPadInl) / 2)
}

@media (scripting: none) {
    .expressive-code .copy {
        display: none
    }
}

.expressive-code .copy {
    direction: ltr;
    unicode-bidi: isolate
}

.expressive-code .copy button {
    position: relative;
    align-self: flex-end;
    margin: 0;
    padding: 0;
    border: none;
    border-radius: 0.2rem;
    z-index: 1;
    cursor: pointer;
    transition-property: opacity, background, border-color;
    transition-duration: 0.2s;
    transition-timing-function: cubic-bezier(0.25, 0.46, 0.45, 0.94);
    width: 2.5rem;
    height: 2.5rem;
    background: var(--code-background);
    opacity: 0.75
}

.expressive-code .copy button div {
    position: absolute;
    inset: 0;
    border-radius: inherit;
    background: var(--ec-frm-inlBtnBg);
    opacity: var(--ec-frm-inlBtnBgIdleOpa);
    transition-property: inherit;
    transition-duration: inherit;
    transition-timing-function: inherit
}

.expressive-code .copy button::before {
    content: '';
    position: absolute;
    pointer-events: none;
    inset: 0;
    border-radius: inherit;
    border: var(--ec-brdWd) solid var(--ec-frm-inlBtnBrd);
    opacity: var(--ec-frm-inlBtnBrdOpa)
}

.expressive-code .copy button::after {
    content: '';
    position: absolute;
    pointer-events: none;
    inset: 0;
    background-color: var(--ec-frm-inlBtnFg);
    -webkit-mask-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='black' stroke-width='1.75'%3E%3Cpath d='M3 19a2 2 0 0 1-1-2V2a2 2 0 0 1 1-1h13a2 2 0 0 1 2 1'/%3E%3Crect x='6' y='5' width='16' height='18' rx='1.5' ry='1.5'/%3E%3C/svg%3E");
    -webkit-mask-repeat: no-repeat;
    mask-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='black' stroke-width='1.75'%3E%3Cpath d='M3 19a2 2 0 0 1-1-2V2a2 2 0 0 1 1-1h13a2 2 0 0 1 2 1'/%3E%3Crect x='6' y='5' width='16' height='18' rx='1.5' ry='1.5'/%3E%3C/svg%3E");
    mask-repeat: no-repeat;
    margin: 0.475rem;
    line-height: 0
}

.expressive-code .copy button:hover, .expressive-code .copy button:focus:focus-visible {
    opacity: 1
}

.expressive-code .copy button:hover div, .expressive-code .copy button:focus:focus-visible div {
    opacity: var(--ec-frm-inlBtnBgHoverOrFocusOpa)
}

.expressive-code .copy button:active {
    opacity: 1
}

.expressive-code .copy button:active div {
    opacity: var(--ec-frm-inlBtnBgActOpa)
}

.expressive-code .copy .feedback {
    --tooltip-arrow-size: 0.35rem;
    --tooltip-bg: var(--ec-frm-tooltipSuccessBg);
    color: var(--ec-frm-tooltipSuccessFg);
    pointer-events: none;
    user-select: none;
    -webkit-user-select: none;
    position: relative;
    align-self: center;
    background-color: var(--tooltip-bg);
    z-index: 99;
    padding: 0.125rem 0.75rem;
    border-radius: 0.2rem;
    margin-inline-end: var(--tooltip-arrow-size);
    opacity: 0;
    transition-property: opacity, transform;
    transition-duration: 0.2s;
    transition-timing-function: ease-in-out;
    transform: translate3d(0, 0.25rem, 0)
}

.expressive-code .copy .feedback::after {
    content: '';
    position: absolute;
    pointer-events: none;
    top: calc(50% - var(--tooltip-arrow-size));
    inset-inline-end: calc(-2 * (var(--tooltip-arrow-size) - 0.5px));
    border: var(--tooltip-arrow-size) solid transparent;
    border-inline-start-color: var(--tooltip-bg)
}

.expressive-code .copy .feedback.show {
    opacity: 1;
    transform: translate3d(0, 0, 0)
}

@media (hover: hover) {
    .expressive-code {
    }

    .expressive-code .copy button {
        opacity: 0;
        width: 2rem;
        height: 2rem
    }

    .expressive-code .frame:hover .copy button:not(:hover), .expressive-code .frame:focus-within :focus-visible ~ .copy button:not(:hover), .expressive-code .frame .copy .feedback.show ~ button:not(:hover) {
        opacity: 0.75
    }
}</style>
<div class="expressive-code">
    <figure class="frame">
        <figcaption class="header"></figcaption>
        <pre data-language="js"><code><div class="ec-line"><div class="code"><span style="--0:#E1E4E8;--1:#24292E">console.</span><span
            style="--0:#B392F0;--1:#6F42C1">log</span><span style="--0:#E1E4E8;--1:#24292E">(</span><span
            style="--0:#9ECBFF;--1:#032F62">"Hello world!"</span><span
            style="--0:#E1E4E8;--1:#24292E">)</span></div></div></code></pre>
        <div class="copy">
            <button title="Copy to clipboard" data-copied="Copied!" data-code="console.log(&#x22;Hello world!&#x22;)">
                <div></div>
            </button>
        </div>
    </figure>
</div>

```

What am I missing?

Thanks in advance!
