### ISSUE TITLE
Add file icon next to the file title in the frame

### ISSUE THREAD

**Issue by Macktireh** [expressive-code/expressive-code#257]
Hi,

I was wondering if it's possible to add a file icon to the left of the file title in the frame? Here's an example to illustrate the request:

![image](https://github.com/user-attachments/assets/53a599b9-42de-4f6b-8ac6-47402d5ac2bb)

Thanks in advance

**Comment by aripalo** [comment]
I just found out about expressive-code so I really don't know how to even begin implementing it. I'm curious too.

But one workaround that comes to mind is that expressive-code seems to set the language into the `pre` elements `data-language` attribute so at least one could achieve something like that via CSS. But of course that would be a bit hacky, and a native or plugin based solution would be more robust.

**Comment by hippotastic** [comment]
Hello! I think this would be easy to do once we have a reliable source of SVG icons for all common file types.

Do you know any libraries that would fit this description? I know I looked earlier this year but couldn't find any.

**Comment by Macktireh** [comment]
@hippotastic There is [Material Icon Theme](https://github.com/material-extensions/vscode-material-icon-theme) for VSCode, which supports a wide range of icons and is very stable. Does that work for you?

**Comment by aripalo** [comment]
So far I've used combinations of various icon sets from https://icon-sets.iconify.design/

Material Icon Theme for VS Code is probably the safest bet, but no matter what the choice, I think in the end it would be good to expose some configuration model for user-defined overrides.

**Comment by hippotastic** [comment]
Thank you for your replies and icon set links, much appreciated!

I'm always trying to keep the amount of meta information users need to add to their code blocks to a minimum by default, so my first thought when I read the feature request was that the plugin could try to automatically determine an icon based on the language and/or file extension (if provided). This would prevent users from having to repeat the same `icon="..."` for every code block.

To also allow adding icons to files that have no recognized language & extension, or when a manual override is desired, I could imagine using an `icon` meta prop as you outlined.

Would that solve your use case?

**Comment by kelvindecosta** [comment]
![Image](https://github.com/user-attachments/assets/f604fda3-a2c6-431d-a9e5-cce509360725)

It is possible to set this up using the following styles:

```css

.expressive-code .frame.has-title:not(.is-terminal) {
  /* Language Icons */
  .title::before {
    content: '';
    @apply iconify-color size-4;
    @apply mr-2 align-middle;
  }

  &:has(pre[data-language='python']) .title::before {
    @apply vscode-icons--file-type-python;
  }

  &:has(pre[data-language='js']) .title::before {
    @apply vscode-icons--file-type-js-official;
  }
```

The above snippet uses [this plugin for Tailwind](https://iconify.design/docs/usage/css/tailwind/), but I'm sure you can modify the `content` property to get the same result.


> [!WARNING]
>
> This can get a bit cumbersome, since you'd need to manually specify the icon for each language.
