### ISSUE TITLE
Feature request: collapsible code section

### ISSUE THREAD

**Issue by birjj** [expressive-code/expressive-code#49]
For long code examples it would be nice to support collapsible code sections. An example of how this can work can be seen in GitHub's PRs:

<div align="center"><a href="https://github.com/expressive-code/expressive-code/assets/4542461/d5359545-0b26-4408-a4a3-ed19f1094364" target="_blank"><img src="https://github.com/expressive-code/expressive-code/assets/4542461/d5359545-0b26-4408-a4a3-ed19f1094364" /></a><br/>(darkened to highlight the sections)</div><br/>

I'm imagining this would be done by using a new marker type, e.g.

````
```js collapse={4-6,8-12}

```
````

**Comment by birjj** [comment]
I had an initial look at it, but might not have time to implement it myself. I'll share my thoughts for now, in case someone else wants to pick it up and implement it as a plugin:

<div align="center"><a href="https://github.com/expressive-code/expressive-code/assets/4542461/c85687c4-8148-4f1b-8a7d-193cc654777e" target="_blank"><img src="https://github.com/expressive-code/expressive-code/assets/4542461/c85687c4-8148-4f1b-8a7d-193cc654777e" width="378" /></a></div><br/>

A decently accessible way to implement this would be by enclosing the affected lines in a `<details>` element:

```html
<code>
  <div class="ec-line">/*...*/</div>
  <details class="ec-collapsible">
    <summary>
      <svg aria-hidden="true" height="16" viewBox="0 0 16 16" width="16"><path d="m8.177.677 2.896 2.896a.25.25 0 0 1-.177.427H8.75v1.25a.75.75 0 0 1-1.5 0V4H5.104a.25.25 0 0 1-.177-.427L7.823.677a.25.25 0 0 1 .354 0ZM7.25 10.75a.75.75 0 0 1 1.5 0V12h2.146a.25.25 0 0 1 .177.427l-2.896 2.896a.25.25 0 0 1-.354 0l-2.896-2.896A.25.25 0 0 1 5.104 12H7.25v-1.25Zm-5-2a.75.75 0 0 0 0-1.5h-.5a.75.75 0 0 0 0 1.5h.5ZM6 8a.75.75 0 0 1-.75.75h-.5a.75.75 0 0 1 0-1.5h.5A.75.75 0 0 1 6 8Zm2.25.75a.75.75 0 0 0 0-1.5h-.5a.75.75 0 0 0 0 1.5h.5ZM12 8a.75.75 0 0 1-.75.75h-.5a.75.75 0 0 1 0-1.5h.5A.75.75 0 0 1 12 8Zm2.25.75a.75.75 0 0 0 0-1.5h-.5a.75.75 0 0 0 0 1.5h.5Z"></path></svg>
      2 collapsed lines
    </summary>
    <div class="ec-line">/*...*/</div>
    <div class="ec-line">/*...*/</div>
  </details>
  <div class="ec-line">/*...*/</div>
</code>
```

In which case a GitHub-like styling can be achieved by:

```css
.ec-collapsible summary::marker { /* hide the default <details> marker */
    display: none;
    content: "";
}
.ec-collapsible summary { /* use GitHub-like styling for the "2 collapsed lines" line */
    cursor: pointer !important;
    padding: 4px 0 4px 22px;
    background: rgba(84 174 255 / 20%);
    color: #939eab;
}
.ec-collapsible summary svg { fill: currentColor; }

.ec-collapsible[open] summary { /* hide the "2 collapse lines" line when the lines are displayed */
    display: none;
}
.ec-collapsible[open] { /* show a GitHub-like background on the lines after it is opened */
    background: rgb(246 248 250 / 7.5%);
    box-shadow: inset 0 -1px rgb(216 222 228 / 10%), inset 0 1px rgb(216 222 228 / 10%);
}
```

What's left is wrapping that up in a plugin, parsing out which lines should be wrapped, handling indentation of the `<summary>` so it matches the surrounding code, and configurability.
